import React, { useState, useEffect, useMemo } from 'react';
import { HexColorPicker } from 'react-colorful';
import { colord, extend } from 'colord';
import namesPlugin from 'colord/plugins/names';
import { Popover, PopoverContent, PopoverTrigger } from '@/components/ui/popover';
import { Input } from '@/components/ui/input';
import { Label } from '@/components/ui/label';
import { Slider } from '@/components/ui/slider';
import { Button } from '@/components/ui/button';
import { Shuffle } from 'lucide-react';
import { cn } from '@/lib/utils';
import { motion, AnimatePresence } from 'framer-motion';

extend([namesPlugin]);

interface AdvancedColorPickerProps {
    value?: string; // Make optional/robust
    color?: string; // Alias for value to match old picker interface if needed, or update usage
    onChange: (value: string) => void;
    className?: string; // Optional styling
    disableGradient?: boolean;
    inline?: boolean; // When true, renders picker content directly without trigger/popover wrapper
    onOpenChange?: (open: boolean) => void;
    children?: React.ReactNode; // Custom trigger content
}

type Mode = 'solid' | 'gradient';

export const AdvancedColorPicker: React.FC<AdvancedColorPickerProps> = ({ value, color, onChange, className, disableGradient = false, inline = false, onOpenChange, children }) => {
    // Handle prop alias
    const actualValue = value || color || '#ffffff';

    // Detect initial mode
    // If value includes 'gradient', start in gradient mode.
    const initialMode = useMemo(() => !disableGradient && actualValue.startsWith('linear-gradient') ? 'gradient' : 'solid', [actualValue, disableGradient]);
    const [mode, setMode] = useState<Mode>(initialMode);

    // Solid State
    const [solidColor, setSolidColor] = useState('#ffffff');
    const [hexInput, setHexInput] = useState('#FFFFFF'); // Local state for typing
    const [opacity, setOpacity] = useState(100);
    const [popoverOpen, setPopoverOpen] = useState(false); // Controlled popover

    // Gradient State (Simple Linear Gradient for MVP)
    const [gradientAngle, setGradientAngle] = useState(180);
    const [gradientStart, setGradientStart] = useState('#ffffff');
    const [gradientEnd, setGradientEnd] = useState('#000000');

    // Parse incoming value on mount / prop change
    useEffect(() => {
        if (!disableGradient && actualValue.startsWith('linear-gradient')) {
            setMode('gradient');
            // Basic regex parsing for: linear-gradient(180deg, #start 0%, #end 100%)
            // This is brittle but sufficient for values generated BY THIS picker.
            try {
                // Regex to capture: angle, start color, end color
                // Expects format: linear-gradient(180deg, ... 0%, ... 100%)
                const match = actualValue.match(/linear-gradient\((\d+)deg,\s*(.+?)\s*0%,\s*(.+?)\s*100%\)/);
                if (match) {
                    setGradientAngle(parseInt(match[1]));
                    setGradientStart(match[2]);
                    setGradientEnd(match[3]);
                }
            } catch (e) {
                console.warn("AdvancedColorPicker: Failed to parse gradient", actualValue);
            }
        } else {
            setMode('solid');
            const c = colord(actualValue);
            if (c.isValid()) {
                setSolidColor(c.toHex()); // Returns #RRGGBB
                setOpacity(Math.round(c.alpha() * 100)); // 0-100
            }
        }
    }, [actualValue, disableGradient]);

    /* --- SOLID HANDLERS --- */

    // Called when HEX picker changes
    const handleHexChange = (newHex: string) => {
        setSolidColor(newHex);
        emitSolid(newHex, opacity);
    };

    // Called when Opacity Input changes
    const handleOpacityChange = (newOpacity: number) => {
        // Clamp 0-100
        const v = Math.max(0, Math.min(100, newOpacity));
        setOpacity(v);
        emitSolid(solidColor, v);
    };

    // Helper to emit the final string
    const emitSolid = (hex: string, op: number) => {
        const c = colord(hex).alpha(op / 100);
        // ALWAYS emit Hex (6 or 8 chars)
        onChange(c.toHex());
    };

    /* --- GRADIENT HANDLERS --- */

    const handleGradientUpdate = (start: string, end: string, angle: number) => {
        setGradientStart(start);
        setGradientEnd(end);
        setGradientAngle(angle);
        // Construct standard CSS linear-gradient string
        const css = `linear-gradient(${angle}deg, ${start} 0%, ${end} 100%)`;
        onChange(css);
    };

    const randomizeGradient = () => {
        const rColor = () => colord({ r: Math.random() * 255, g: Math.random() * 255, b: Math.random() * 255 }).toHex();
        const rAngle = Math.floor(Math.random() * 360);
        handleGradientUpdate(rColor(), rColor(), rAngle);
    };

    // Handle direct hex input change
    const handleDirectHexChange = (e: React.ChangeEvent<HTMLInputElement>) => {
        let inputVal = e.target.value;
        // Always update the input display
        setHexInput(inputVal.toUpperCase());

        // Parse and apply if valid
        let hex = inputVal.replace('#', '').toUpperCase();
        if (hex.length === 6 || hex.length === 3) {
            if (/^[0-9A-F]+$/.test(hex)) {
                const fullHex = '#' + hex;
                const c = colord(fullHex);
                if (c.isValid()) {
                    setSolidColor(c.toHex());
                    emitSolid(c.toHex(), opacity);
                }
            }
        }
    };

    // Handle Enter key to expand shorthand hex (e.g., F -> FFFFFF, AB -> ABABAB, 0 -> 000000)
    const handleHexKeyDown = (e: React.KeyboardEvent<HTMLInputElement>) => {
        if (e.key === 'Enter') {
            e.preventDefault(); // Prevent closing popover/submitting form
            let hex = hexInput.replace('#', '').toUpperCase();
            let expandedHex = '';

            // Handle "0" -> "000000", "F" -> "FFFFFF"
            // Single char: repeat 6 times
            if (hex.length === 1 && /^[0-9A-F]$/.test(hex)) {
                expandedHex = hex.repeat(6);
            }
            // Two chars: repeat 3 times (e.g., 00 -> 000000, FF -> FFFFFF)
            else if (hex.length === 2 && /^[0-9A-F]+$/.test(hex)) {
                expandedHex = hex.repeat(3);
            }
            // Valid 3 or 6 char hex: use as-is
            else if ((hex.length === 3 || hex.length === 6) && /^[0-9A-F]+$/.test(hex)) {
                expandedHex = hex.length === 3 ? hex[0] + hex[0] + hex[1] + hex[1] + hex[2] + hex[2] : hex;
            }

            if (expandedHex) {
                const fullHex = '#' + expandedHex;
                setHexInput(fullHex);
                const c = colord(fullHex);
                if (c.isValid()) {
                    setSolidColor(c.toHex());
                    emitSolid(c.toHex(), opacity);
                }
                // Removed setPopoverOpen(false) so it stays open
                // Optionally blur to indicate "done" typing
                (e.target as HTMLInputElement).blur();
            }
        }
    };

    // Sync hexInput when solidColor changes from picker
    useEffect(() => {
        setHexInput(solidColor.toUpperCase());
    }, [solidColor]);

    // Inline mode: render just the picker content without trigger/popover (for embedded usage)
    if (inline) {
        return (
            <div className={cn("w-64 p-3 bg-popover rounded-md border", className)}>
                {mode === 'solid' ? (
                    <div className="space-y-3">
                        {/* REACT-COLORFUL HEX PICKER */}
                        <div className="custom-color-picker wrapper">
                            <HexColorPicker
                                color={solidColor}
                                onChange={handleHexChange}
                                style={{ width: '100%', height: '140px', borderRadius: '8px' }}
                            />
                        </div>

                        {/* INPUTS ROW */}
                        <div className="flex gap-2 items-end">
                            {/* Hex Input */}
                            <div className="space-y-1 flex-1">
                                <Label className="text-[9px] text-muted-foreground uppercase tracking-wider font-semibold">Hex</Label>
                                <div className="relative flex items-center">
                                    <span className="absolute left-2 text-[10px] text-muted-foreground">#</span>
                                    <Input
                                        type="text"
                                        value={hexInput.replace('#', '')}
                                        onChange={(e) => {
                                            const val = e.target.value.toUpperCase();
                                            setHexInput('#' + val);
                                            // Apply if valid
                                            if ((val.length === 6 || val.length === 3) && /^[0-9A-F]+$/.test(val)) {
                                                const c = colord('#' + val);
                                                if (c.isValid()) {
                                                    setSolidColor(c.toHex());
                                                    emitSolid(c.toHex(), opacity);
                                                }
                                            }
                                        }}
                                        className="h-7 pl-4 text-[10px] font-mono uppercase bg-background border-input focus-visible:ring-1"
                                        maxLength={6}
                                    />
                                </div>
                            </div>

                            {/* Opacity Input */}
                            <div className="space-y-1 w-16">
                                <Label className="text-[9px] text-muted-foreground uppercase tracking-wider font-semibold">Opacity</Label>
                                <div className="relative flex items-center">
                                    <Input
                                        type="number"
                                        min={0}
                                        max={100}
                                        value={opacity}
                                        onChange={(e) => handleOpacityChange(parseInt(e.target.value) || 0)}
                                        className="h-7 pr-4 text-[10px] font-mono text-center bg-background border-input focus-visible:ring-1 [appearance:textfield] [&::-webkit-outer-spin-button]:appearance-none [&::-webkit-inner-spin-button]:appearance-none"
                                    />
                                    <span className="absolute right-1.5 text-[9px] text-muted-foreground">%</span>
                                </div>
                            </div>
                        </div>
                    </div>
                ) : null}
            </div>
        );
    }

    return (
        <div
            className={cn(
                "flex items-center gap-2 p-1 rounded-md border bg-background h-9 w-full",
                className
            )}
        >
            {/* Color Swatch - Opens Popover */}
            <Popover
                open={popoverOpen}
                onOpenChange={(open) => {
                    setPopoverOpen(open);
                    onOpenChange?.(open);
                }}
            >
                <PopoverTrigger asChild>
                    {children ? (
                        children
                    ) : (
                        <div className="w-6 h-6 rounded border shadow-sm shrink-0 relative overflow-hidden cursor-pointer hover:ring-2 hover:ring-primary/50 transition-all">
                            <div className="absolute inset-0 z-0 opacity-100"
                                style={{
                                    backgroundImage: `
                                linear-gradient(45deg, #ccc 25%, transparent 25%), 
                                linear-gradient(-45deg, #ccc 25%, transparent 25%), 
                                linear-gradient(45deg, transparent 75%, #ccc 75%), 
                                linear-gradient(-45deg, transparent 75%, #ccc 75%)
                              `,
                                    backgroundSize: '8px 8px',
                                    backgroundPosition: '0 0, 0 4px, 4px -4px, -4px 0px'
                                }}
                            />
                            <div className="absolute inset-0 z-10" style={{ background: actualValue }} />
                        </div>
                    )}
                </PopoverTrigger>

                <AnimatePresence>
                    {popoverOpen && (
                        <PopoverContent
                            forceMount
                            asChild
                            className="w-64 p-0 overflow-hidden bg-transparent border-none shadow-none"
                            align="start"
                            sideOffset={8}
                        >
                            <motion.div
                                initial={{ opacity: 0, scale: 0.9, y: 10, filter: 'blur(10px)' }}
                                animate={{ opacity: 1, scale: 1, y: 0, filter: 'blur(0px)' }}
                                exit={{ opacity: 0, scale: 0.95, y: 5, filter: 'blur(10px)' }}
                                transition={{ type: "spring", damping: 20, stiffness: 300 }}
                                className="w-64 p-3 bg-white dark:bg-zinc-950 border border-zinc-200 dark:border-zinc-800 shadow-2xl rounded-2xl backdrop-blur-xl"
                            >
                                <style dangerouslySetInnerHTML={{
                                    __html: `
                                    .custom-color-picker .react-colorful__pointer {
                                        width: 20px;
                                        height: 20px;
                                        border: 3px solid white;
                                        box-shadow: 0 4px 12px rgba(0,0,0,0.3);
                                        transition: transform 0.15s cubic-bezier(0.175, 0.885, 0.32, 1.275);
                                    }
                                    .custom-color-picker .react-colorful__pointer--active {
                                        transform: scale(1.3);
                                    }
                                    .custom-color-picker .react-colorful__hue {
                                        height: 12px;
                                        border-radius: 6px;
                                        margin-top: 12px;
                                    }
                                    .custom-color-picker .react-colorful__saturation {
                                        border-radius: 12px;
                                        border-bottom: none;
                                    }
                                `}} />

                                {/* Mode Tabs (Simple Toggle) */}
                                {!disableGradient && (
                                    <div className="grid grid-cols-2 gap-1 bg-muted p-1 rounded-lg mb-3">
                                        <button
                                            className={cn(
                                                "text-[10px] py-1 rounded-md font-medium transition-all text-center",
                                                mode === 'solid' ? "bg-background shadow text-foreground" : "text-muted-foreground hover:text-foreground hover:bg-background/50"
                                            )}
                                            onClick={() => {
                                                setMode('solid');
                                                emitSolid(solidColor, opacity);
                                            }}
                                        >
                                            Solid
                                        </button>
                                        <button
                                            className={cn(
                                                "text-[10px] py-1 rounded-md font-medium transition-all text-center",
                                                mode === 'gradient' ? "bg-background shadow text-foreground" : "text-muted-foreground hover:text-foreground hover:bg-background/50"
                                            )}
                                            onClick={() => {
                                                setMode('gradient');
                                                handleGradientUpdate(gradientStart, gradientEnd, gradientAngle);
                                            }}
                                        >
                                            Gradient
                                        </button>
                                    </div>
                                )}

                                {mode === 'solid' ? (
                                    <div className="space-y-3">
                                        {/* REACT-COLORFUL HEX PICKER */}
                                        <div className="custom-color-picker wrapper">
                                            <HexColorPicker
                                                color={solidColor}
                                                onChange={handleHexChange}
                                                style={{ width: '100%', height: '140px', borderRadius: '8px' }}
                                            />
                                        </div>

                                        {/* INPUTS ROW */}
                                        <div className="flex gap-2 items-end">
                                            {/* Hex Input */}
                                            <div className="space-y-1 flex-1">
                                                <Label className="text-[9px] text-muted-foreground uppercase tracking-wider font-semibold">Hex</Label>
                                                <div className="relative flex items-center">
                                                    <span className="absolute left-2 text-[10px] text-muted-foreground">#</span>
                                                    <Input
                                                        type="text"
                                                        value={hexInput.replace('#', '')}
                                                        onChange={(e) => {
                                                            const val = e.target.value.toUpperCase();
                                                            setHexInput('#' + val);
                                                            // Apply if valid
                                                            if ((val.length === 6 || val.length === 3) && /^[0-9A-F]+$/.test(val)) {
                                                                const c = colord('#' + val);
                                                                if (c.isValid()) {
                                                                    setSolidColor(c.toHex());
                                                                    emitSolid(c.toHex(), opacity);
                                                                }
                                                            }
                                                        }}
                                                        onKeyDown={(e) => {
                                                            if (e.key === 'Enter') {
                                                                let hex = hexInput.replace('#', '').toUpperCase();
                                                                let expandedHex = '';

                                                                // Single char: repeat 6 times (F -> FFFFFF)
                                                                if (hex.length === 1 && /^[0-9A-F]$/.test(hex)) {
                                                                    expandedHex = hex.repeat(6);
                                                                }
                                                                // Two chars: repeat 3 times (FF -> FFFFFF)
                                                                else if (hex.length === 2 && /^[0-9A-F]+$/.test(hex)) {
                                                                    expandedHex = hex.repeat(3);
                                                                }
                                                                // Valid 3 or 6 char hex: use as-is
                                                                else if ((hex.length === 3 || hex.length === 6) && /^[0-9A-F]+$/.test(hex)) {
                                                                    expandedHex = hex.length === 3 ? hex[0] + hex[0] + hex[1] + hex[1] + hex[2] + hex[2] : hex;
                                                                }

                                                                if (expandedHex) {
                                                                    const fullHex = '#' + expandedHex;
                                                                    setHexInput(fullHex);
                                                                    const c = colord(fullHex);
                                                                    if (c.isValid()) {
                                                                        setSolidColor(c.toHex());
                                                                        emitSolid(c.toHex(), opacity);
                                                                    }
                                                                    // Close popover on Enter
                                                                    setPopoverOpen(false);
                                                                }
                                                            }
                                                        }}
                                                        className="h-7 pl-4 text-[10px] font-mono uppercase bg-background border-input focus-visible:ring-1"
                                                        maxLength={6}
                                                    />
                                                </div>
                                            </div>

                                            {/* Opacity Input (No Slider) */}
                                            <div className="space-y-1 w-16">
                                                <Label className="text-[9px] text-muted-foreground uppercase tracking-wider font-semibold">Opacity</Label>
                                                <div className="relative flex items-center">
                                                    <Input
                                                        type="number"
                                                        min={0}
                                                        max={100}
                                                        value={opacity}
                                                        onChange={(e) => handleOpacityChange(parseInt(e.target.value) || 0)}
                                                        className="h-7 pr-4 text-[10px] font-mono text-center bg-background border-input focus-visible:ring-1 [appearance:textfield] [&::-webkit-outer-spin-button]:appearance-none [&::-webkit-inner-spin-button]:appearance-none"
                                                    />
                                                    <span className="absolute right-1.5 text-[9px] text-muted-foreground">%</span>
                                                </div>
                                            </div>
                                        </div>
                                    </div>
                                ) : (
                                    <div className="space-y-3">
                                        {/* Gradient Preview Bar */}
                                        <div
                                            className="w-full h-20 rounded-lg border shadow-sm mb-2"
                                            style={{
                                                background: `linear-gradient(${gradientAngle}deg, ${gradientStart} 0%, ${gradientEnd} 100%)`,
                                                backgroundImage: `
                                    linear-gradient(${gradientAngle}deg, ${gradientStart} 0%, ${gradientEnd} 100%),
                                    linear-gradient(45deg, #ccc 25%, transparent 25%), 
                                    linear-gradient(-45deg, #ccc 25%, transparent 25%), 
                                    linear-gradient(45deg, transparent 75%, #ccc 75%), 
                                    linear-gradient(-45deg, transparent 75%, #ccc 75%)
                                `,
                                                backgroundSize: '100% 100%, 10px 10px, 10px 10px, 10px 10px, 10px 10px' // Add checkerboard behind gradient for transparency awareness? (optional)
                                            }}
                                        />

                                        {/* Angle Slider */}
                                        <div className="space-y-1.5">
                                            <div className="flex justify-between items-center">
                                                <Label className="text-[9px] text-muted-foreground uppercase font-semibold">Angle</Label>
                                                <span className="text-[9px] font-mono text-muted-foreground">{gradientAngle}°</span>
                                            </div>
                                            <Slider
                                                value={[gradientAngle]}
                                                max={360}
                                                step={1}
                                                onValueChange={(vals) => handleGradientUpdate(gradientStart, gradientEnd, vals[0])}
                                                className="[&_.bg-primary]:bg-foreground/50" // Stylistic tweak
                                            />
                                        </div>

                                        {/* Stops Selection */}
                                        <div className="grid grid-cols-2 gap-2 mt-2">
                                            <div className="space-y-1">
                                                <Label className="text-[9px] text-muted-foreground uppercase font-semibold">Start Color</Label>
                                                <div className="h-7 flex items-center border rounded-md px-1 bg-background">
                                                    <input
                                                        type="color"
                                                        value={gradientStart}
                                                        onChange={(e) => handleGradientUpdate(e.target.value, gradientEnd, gradientAngle)}
                                                        className="h-5 w-5 rounded-sm p-0 border-0 cursor-pointer bg-transparent"
                                                    />
                                                    <span className="text-[9px] ml-1.5 font-mono uppercase text-muted-foreground truncate">{gradientStart}</span>
                                                </div>
                                            </div>

                                            <div className="space-y-1">
                                                <Label className="text-[9px] text-muted-foreground uppercase font-semibold">End Color</Label>
                                                <div className="h-7 flex items-center border rounded-md px-1 bg-background">
                                                    <input
                                                        type="color"
                                                        value={gradientEnd}
                                                        onChange={(e) => handleGradientUpdate(gradientStart, e.target.value, gradientAngle)}
                                                        className="h-5 w-5 rounded-sm p-0 border-0 cursor-pointer bg-transparent"
                                                    />
                                                    <span className="text-[9px] ml-1.5 font-mono uppercase text-muted-foreground truncate">{gradientEnd}</span>
                                                </div>
                                            </div>
                                        </div>

                                        {/* Randomize Button */}
                                        <Button
                                            variant="secondary"
                                            size="sm"
                                            className="w-full text-[10px] h-7 mt-1 font-medium text-muted-foreground hover:text-foreground"
                                            onClick={randomizeGradient}
                                        >
                                            <Shuffle className="w-3 h-3 mr-1.5" />
                                            Randomize
                                        </Button>
                                    </div>
                                )}
                            </motion.div>
                        </PopoverContent>
                    )}
                </AnimatePresence>
            </Popover>

            {/* Editable Hex Input - Direct editing without opening popover */}
            {mode === 'solid' ? (
                <input
                    type="text"
                    value={hexInput}
                    onChange={handleDirectHexChange}
                    onKeyDown={handleHexKeyDown}
                    onClick={(e) => e.stopPropagation()}
                    className="flex-1 h-7 px-2 text-[10px] font-mono uppercase bg-transparent border-0 outline-none focus:ring-0 text-foreground placeholder:text-muted-foreground"
                    maxLength={7}
                    placeholder="#000000"
                />
            ) : (
                <span className="text-[10px] font-mono text-muted-foreground uppercase truncate flex-1">
                    Gradient
                </span>
            )}
        </div>
    );
};
